In [3]:
import numpy as np

In [16]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print a

print a.shape

print a.ndim  # rank

print a[0]

print a[1,0]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3L, 3L)
2
[1 2 3]
4


In [17]:
a = np.arange(15).reshape(3, 5)

print a

print a.shape

print a.ndim

print a.dtype.name

print a.size

print type(a)

print a[1,1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3L, 5L)
2
int32
15
<type 'numpy.ndarray'>
6


In [21]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [23]:
np.ones((3,4), dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [28]:
np.arange(10,30,0.5) # step value can be float

array([ 10. ,  10.5,  11. ,  11.5,  12. ,  12.5,  13. ,  13.5,  14. ,
        14.5,  15. ,  15.5,  16. ,  16.5,  17. ,  17.5,  18. ,  18.5,
        19. ,  19.5,  20. ,  20.5,  21. ,  21.5,  22. ,  22.5,  23. ,
        23.5,  24. ,  24.5,  25. ,  25.5,  26. ,  26.5,  27. ,  27.5,
        28. ,  28.5,  29. ,  29.5])

In [29]:
np.arange(10)  # 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.linspace(0,2,9)  # # 9 floating point numbers from 0 to 2 

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

#### Arithmetic operations

Arithmetic operators on arrays apply elementwise

In [38]:
a = np.arange(4).reshape((2,2))
print a

b = np.arange(10,14).reshape((2,2))
print b

print a+b 
print b-a
print a*b
print a**2
print a<2
print 10*np.sin(a)

[[0 1]
 [2 3]]
[[10 11]
 [12 13]]
[[10 12]
 [14 16]]
[[10 10]
 [10 10]]
[[ 0 11]
 [24 39]]
[[0 1]
 [4 9]]
[[ True  True]
 [False False]]
[[ 0.          8.41470985]
 [ 9.09297427  1.41120008]]


The matrix product can be performed using the dot function or method

In [39]:
a.dot(b)

array([[12, 13],
       [56, 61]])

In [41]:
np.dot(a,b) # Another way

array([[12, 13],
       [56, 61]])

In [45]:
a = np.random.random((2,3))
print a

print a.sum()
print a.min()
print a.max()

[[ 0.07386989  0.62717617  0.28669175]
 [ 0.42475502  0.46288541  0.04424437]]
1.91962260415
0.0442443745197
0.627176172207


In [47]:
print a.sum(axis=0) # columns, opposite to pandas
print a.sum(axis=1) # rows, opposite to pandas

[ 0.4986249   1.09006158  0.33093612]
[ 0.9877378  0.9318848]


Multidimensional arrays can have one index per axis

In [52]:
a = np.arange(25).reshape((5,5))
print a

print a[0:4, :]     # first 4 rows, all columns
print a[:, 0:2]   # all rows, first 2 columns 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]


In [54]:
# Iterating over multidimensional array row-wise
for row in a:
    print row

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [55]:
# Iterating over multidimensional array element-wise
for element in a.flat:
    print element

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [56]:
print a.T # Transpose of array

[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [57]:
a.T.shape

(5L, 5L)

In [61]:
a = np.floor(10*np.random.random((2,2)))
print a

b = np.floor(10*np.random.random((2,2)))
print b

print np.vstack((a,b)) # vertically stack arrays
print np.hstack((a,b)) # horizontally stack arrays


[[ 8.  5.]
 [ 8.  2.]]
[[ 8.  2.]
 [ 8.  0.]]
[[ 8.  5.]
 [ 8.  2.]
 [ 8.  2.]
 [ 8.  0.]]
[[ 8.  5.  8.  2.]
 [ 8.  2.  8.  0.]]


#### Linear Algebra

In [63]:
# L0, L1 and L2 norm of a vector 
x = np.array([3,2,-1])
print np.linalg.norm(x,ord=0)  # Number of non-zero elements in vector
print np.linalg.norm(x,ord=1)  # Sum of absolute values of elements in vector
print np.linalg.norm(x,ord=2)  # Euclidesan distance from origin


3.0
6.0
3.74165738677


In [4]:
# Argmin
a = np.arange(6).reshape(2,3)
print a
print np.argmin(a)
print np.argmin(a, axis=0) # Returns the indices of the maximum values along an axis, per column
print np.argmin(a, axis=1) # Returns the indices of the maximum values along an axis, per row

[[0 1 2]
 [3 4 5]]
0
[0 0 0]
[0 0]


In [5]:
# Argmax
a = np.arange(6).reshape(2,3)
print a
print np.argmax(a)
print np.argmax(a, axis=0) # Returns the indices of the maximum values along an axis, per column
print np.argmax(a, axis=1) # Returns the indices of the maximum values along an axis, per row

[[0 1 2]
 [3 4 5]]
5
[1 1 1]
[2 2]
